Repository moritzzimmer/terraform-aws-lambda, pull requests merged in 2022-12, with the labels that each got.

#76 feat: added pr title validation
  .github/workflows/pr-title.yaml
  .github/workflows/static-analysis.yaml
  README.md
  docs/part1.md
Labels: 📖 documentation, 💅 enhancement

#75 feat: add ephemeral storage configuration
  README.md
  docs/deployment/part2.md
  docs/part2.md
  main.tf
  modules/deployment/README.md
  variables.tf
Labels: 💅 enhancement

#78 chore: removed ignored attributes computed by aws provider
  main.tf
Labels: 💅 enhancement

#80 docs: use pre-commit to generate terraform_docs
  .pre-commit-config.yaml
  Makefile
  README.md
  docs/deployment/part1.md
  docs/deployment/part2.md
  docs/part1.md
  docs/part2.md
  examples/container-image/README.md
  examples/deployment/container-image/README.md
  examples/deployment/s3/README.md
  examples/simple/README.md
  examples/with-cloudwatch-event-rules/README.md
  examples/with-cloudwatch-logs-subscription/README.md
  examples/with-event-source-mappings/dynamodb-with-alias/README.md
  examples/with-event-source-mappings/kinesis/README.md
  examples/with-event-source-mappings/sqs/README.md
  examples/with-sns-subscriptions/README.md
  modules/deployment/README.md
Labels: 📖 documentation

#81 fix: reverted lifecycle ignores
  main.tf
Labels: 🐛 bug
