Repository moritzzimmer/terraform-aws-lambda, pull requests merged in 2023-09, with the labels that each got.

#96 feat(deployment)!: use s3 native notifications over cloudtrail logging
  .tflint.hcl
  README.md
  docs/deployment/deployment.drawio.svg
  docs/deployment/deployment.png
  docs/deployment/docs.drawio
  examples/deployment/complete/README.md
  examples/deployment/complete/main.tf
  examples/deployment/s3/README.md
  examples/deployment/s3/main.tf
  modules/deployment/README.md
  modules/deployment/trigger_s3.tf
  modules/deployment/variables.tf
Labels: 📖 documentation, 💅 enhancement, 💥 breaking change

#97 chore(deployment): bumped default base image for CodeBuild
  modules/deployment/README.md
  modules/deployment/variables.tf
Labels: 💅 enhancement, dependencies

#99 chore(deployment): use python 3.11 in CodeBuild
  modules/deployment/codebuild.tf
Labels: dependencies

#98 chore!: bumped minimum terraform and aws provider versions
  .github/workflows/static-analysis.yaml
  .pre-commit-config.yaml
  .tflint.hcl
  Makefile
  README.md
  examples/container-image/README.md
  examples/container-image/versions.tf
  examples/deployment/complete/README.md
  examples/deployment/complete/main.tf
  examples/deployment/complete/versions.tf
  examples/deployment/container-image/README.md
  examples/deployment/container-image/versions.tf
  examples/deployment/s3/README.md
  examples/deployment/s3/main.tf
  examples/deployment/s3/versions.tf
  examples/fixtures/versions.tf
  examples/simple/README.md
  examples/simple/versions.tf
  examples/with-cloudwatch-event-rules/README.md
  examples/with-cloudwatch-event-rules/versions.tf
  examples/with-cloudwatch-logs-subscription/README.md
  examples/with-cloudwatch-logs-subscription/versions.tf
  examples/with-event-source-mappings/dynamodb-with-alias/README.md
  examples/with-event-source-mappings/dynamodb-with-alias/versions.tf
  examples/with-event-source-mappings/kinesis/README.md
  examples/with-event-source-mappings/kinesis/versions.tf
  examples/with-event-source-mappings/sqs/README.md
  examples/with-event-source-mappings/sqs/versions.tf
  examples/with-sns-subscriptions/README.md
  examples/with-sns-subscriptions/versions.tf
  modules/deployment/README.md
  modules/deployment/versions.tf
  test/go.mod
  test/go.sum
  versions.tf
Labels: 💥 breaking change, dependencies

#101 docs: fixed some documentation issues
  README.md
  modules/deployment/README.md
Labels: 📖 documentation

#100 feat: dynamically configurable post deployment stages
  .github/workflows/static-analysis.yaml
  README.md
  examples/deployment/complete/README.md
  examples/deployment/complete/codepipeline_step.tf
  examples/deployment/complete/codepipeline_step/buildspec.yml
  examples/deployment/complete/codepipeline_step/step.py
  examples/deployment/complete/hook/hook.py
  examples/deployment/complete/main.tf
  modules/deployment/README.md
  modules/deployment/main.tf
  modules/deployment/outputs.tf
  modules/deployment/variables.tf
  versions.tf
Labels: 💅 enhancement
